[.NET10] multi-target `net8.0-android;net10.0-android` (#1118)
Context: https://github.com/dotnet/maui/pull/28997
Context: https://github.com/dotnet/android-libraries/pull/1148

.NET 10 binding assemblies have changes to generate better code to
support trimming and NativeAOT scenarios.

We want to ship a copy of .NET 10 assemblies alongside their `net8.0-android`
counterparts.

To verify API compatibility between the `net8.0-android` and `net10.0-android`
assemblies you can run:

    dotnet tool install --global Microsoft.DotNet.ApiCompat.Tool
    Get-Item *.nupkg | ForEach-Object { Write-Output "apicompat package $_" ; & apicompat package $_.Name 2>&1 | ForEach-Object { "$_" } } > apidiff.txt

At first, we saw ~452 errors, but all appear to be due to changes toward
"hiding" internal Kotlin members in .NET 9:

* https://github.com/dotnet/java-interop/commit/06214ffb9a7645616fed5594860ff62e48d2ff1c

General list of changes:

* Update `_PackageLevelCustomizations.cshtml`
* metadata + Additions cleanup for net10.0
* `nuget.config` from dotnet/android added
* <CheckEolWorkloads>false</CheckEolWorkloads> needed to work around some warnings and errors
* Create nuget-install.cake
* Provision `platforms/android-34`
* `Update Metadata.xml`

    obj/Controls.DeviceTests/Debug/net10.0-android/android/src/mono/androidx/recyclerview/widget/RecyclerView_ItemAnimator_ItemAnimatorListenerImplementor.java(8,57): javac error JAVAC0000:  error: ItemAnimatorListener is not public in ItemAnimator; cannot be accessed from outside package

* [build] remove `Install extra Android SDK packages`
* `$(AndroidManifestType)=GoogleV2`

    Warning : Dependency `platforms;android-36` should have been installed but could not be resolved. You can attempt to install it with...

* Restore BaseOnOffsetChangedListener metadata.xml

    javac.exe error JAVAC0000:  error: BaseOnOffsetChangedListener cannot be inherited with different arguments: <com.google.android.material.appbar.AppBarLayout> and <>

* Fix javac error for `ActivityChooserModel`

    Xamarin.Android.Javac.targets(161,5): error XAJVC0000: C:\a\_work\1\s\artifacts\obj\Benchmarks.Droid\Release\net10.0-android\android-arm64\android\src\mono\androidx\appcompat\widget\ActivityChooserModel_OnChooseActivityListenerImplementor.java:8: error: package androidx.appcompat.widget.ActivityChooserModel does not exist
Xamarin.Android.Javac.targets(161,5): error XAJVC0000: 		androidx.appcompat.widget.ActivityChooserModel.OnChooseActivityListener
Xamarin.Android.Javac.targets(161,5): error XAJVC0000: 		                                              ^

Co-authored-by: Peter Collins <pecolli@microsoft.com>
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>